In [ ]:
import tensorflow as tf
import numpy as np

rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

r1 = tf.constant(9, tf.int16)
print(r1)
r1_float = tf.constant(1.12, tf.float32)
print(r1_float)
r1_string = tf.constant('Hello Vanlang University', tf.string)
print(r1_string)

rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

rank_2_tensor = tf.constant([[1,2],[3,4],[5,6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello Vanlang University', shape=(), dtype=string)
tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)
tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [ ]:
rank_3_tensor = tf.constant([
    [[0,1,2,3,4],
     [5,6,7,8,9]],
    [[10,11,12,13,14],
     [15,16,17,18,19]],
    [[20,21,22,23,24],
     [25,26,27,28,29]],])
print(rank_3_tensor)

print('shape:', rank_3_tensor.shape)
print('type of tensor:' , rank_3_tensor.dtype)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
shape: (3, 2, 5)
type of tensor: <dtype: 'int32'>


In [ ]:
#bai 1
import tensorflow as tf
tensor_zeros = tf.zeros([2,3])

print(tensor_zeros)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [ ]:
#bai 2
import tensorflow as tf
x=tf.constant([[1,2,3],[4,5,6]])

tensor_zeros_1 = tf.zeros_like(x)

tensor_zeros_2 = tf.zeros(shape=x.shape, dtype=x.dtype)

print("Tensor X:\n", x)
print("\nTensor mới (zeros_like):\n", tensor_zeros_1)


Tensor X:
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

Tensor mới (zeros_like):
 tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


In [ ]:
#bai3
import tensorflow as tf

tensor_five = tf.fill([2,3], 5)

print(tensor_five)

tf.Tensor(
[[5 5 5]
 [5 5 5]], shape=(2, 3), dtype=int32)


In [ ]:
#bai4
import tensorflow as tf
tensor_4 = tf.linspace(5.0,10.0,50)

print(tensor_4)

tf.Tensor(
[ 5.         5.102041   5.2040815  5.3061223  5.408163   5.5102043
  5.612245   5.714286   5.8163266  5.9183674  6.020408   6.122449
  6.2244897  6.3265305  6.4285717  6.5306125  6.632653   6.734694
  6.836735   6.9387755  7.0408163  7.1428576  7.244898   7.346939
  7.4489794  7.5510206  7.6530614  7.755102   7.857143   7.9591837
  8.061225   8.163265   8.265306   8.367347   8.469388   8.571428
  8.67347    8.775511   8.877551   8.979592   9.081633   9.183674
  9.285715   9.387755   9.489796   9.591837   9.693878   9.795918
  9.897959  10.       ], shape=(50,), dtype=float32)


In [ ]:
#bai5
import tensorflow as tf
tensor_5= tf.range(start=10, limit=101, delta =2)

print(tensor_5)

tf.Tensor(
[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100], shape=(46,), dtype=int32)


In [2]:
#bai6
import tensorflow as tf


random_normal_tensor = tf.random.normal(
    shape=[3, 2],
    mean=0.0,
    stddev=2.0
)

print(random_normal_tensor)

tf.Tensor(
[[ 2.4085424  -0.13970196]
 [ 2.0900156  -0.80026287]
 [ 2.5381472  -0.60150737]], shape=(3, 2), dtype=float32)


In [3]:
#bai7
import tensorflow as tf

random_uniform_tensor = tf.random.uniform(
    shape=[3, 2],
    minval=0,
    maxval=2
)

print(random_uniform_tensor)


tf.Tensor(
[[1.4236481  1.0224178 ]
 [0.70512843 0.957618  ]
 [1.5902236  0.32615876]], shape=(3, 2), dtype=float32)


In [2]:
#bai8
import tensorflow as tf

X = tf.constant([[1, 2], [3, 4], [5, 6]])


shuffled_X = tf.random.shuffle(X)

print("Tensor X ban đầu:\n", X.numpy())
print("\nTensor X sau khi shuffle:\n", shuffled_X.numpy())

Tensor X ban đầu:
 [[1 2]
 [3 4]
 [5 6]]

Tensor X sau khi shuffle:
 [[1 2]
 [5 6]
 [3 4]]


In [3]:
#bai9
import tensorflow as tf

tensor_origin = tf.random.uniform(shape=[10, 10, 3], minval=0, maxval=255, dtype=tf.int32)


tensor_cropped = tf.image.random_crop(value=tensor_origin, size=[5, 5, 3])

print("Kích thước ban đầu:", tensor_origin.shape)
print("Kích thước sau khi cắt:", tensor_cropped.shape)
print("\nGiá trị của tensor sau khi cắt:\n", tensor_cropped.numpy())

Kích thước ban đầu: (10, 10, 3)
Kích thước sau khi cắt: (5, 5, 3)

Giá trị của tensor sau khi cắt:
 [[[186  80 206]
  [196  64 179]
  [193  83  80]
  [ 43 195 201]
  [ 41  48  90]]

 [[ 97 164 214]
  [212  80 143]
  [190 235 160]
  [136 160 161]
  [ 56   7  19]]

 [[ 30 222 187]
  [ 29 128 152]
  [ 20 209 103]
  [ 65  95  51]
  [165  37 243]]

 [[ 35 226 235]
  [241  65 177]
  [102  89 188]
  [254 145  49]
  [ 35 101 206]]

 [[ 56 127  59]
  [236  12 146]
  [226 173 241]
  [ 82 131  92]
  [ 26  75 163]]]


In [4]:
#bai10
import tensorflow as tf


x = tf.random.uniform(shape=[5], minval=0, maxval=10)
y = tf.random.uniform(shape=[5], minval=0, maxval=10)


result = tf.where(x < y, x + y, x - y)

print("Tensor x:", x.numpy())
print("Tensor y:", y.numpy())
print("Kết quả:", result.numpy())

Tensor x: [5.78463   9.345489  9.3960285 8.933339  4.0219617]
Tensor y: [9.001177   6.36012    7.06194    0.13415575 1.1862445 ]
Kết quả: [14.785807   2.9853687  2.3340883  8.799183   2.8357172]


In [5]:
#bai11
import tensorflow as tf


x = tf.random.uniform(shape=[3, 2], minval=5, maxval=10)

y = tf.random.uniform(shape=[2, 3], minval=15, maxval=20)


diag_x = tf.linalg.diag_part(x)


y_transposed = tf.transpose(y)
result = tf.add(x, y_transposed)

print("Tensor x:\n", x.numpy())
print("\nĐường chéo của x:", diag_x.numpy())
print("\nKết quả x + y (sau khi chuyển vị y):\n", result.numpy())

Tensor x:
 [[7.8458347 5.6719894]
 [7.41353   8.53706  ]
 [7.0234146 8.074331 ]]

Đường chéo của x: [7.8458347 8.53706  ]

Kết quả x + y (sau khi chuyển vị y):
 [[26.07306  22.023407]
 [24.163454 25.3622  ]
 [26.104778 25.123774]]


In [6]:
#bai12
import tensorflow as tf


def create_random_tensors():

    x = tf.random.normal(shape=(3, 2, 2))
    y = tf.random.normal(shape=(3, 2, 2))
    return x, y


@tf.function
def math_operations_graph(x, y):

    addition = tf.add(x, y)
    subtraction = tf.subtract(x, y)
    multiplication = tf.multiply(x, y)
    division = tf.divide(x, y)

    return addition, subtraction, multiplication, division


tensor_x, tensor_y = create_random_tensors()


res_add, res_sub, res_mul, res_div = math_operations_graph(tensor_x, tensor_y)


print("Tensor X ngẫu nhiên:\n", tensor_x.numpy())
print("\nKết quả phép cộng (Graph Execution):\n", res_add.numpy())

Tensor X ngẫu nhiên:
 [[[ 1.5487671  -0.0444896 ]
  [-1.0152519  -0.3118481 ]]

 [[ 0.6737345  -0.94287854]
  [-1.0998572   1.6635281 ]]

 [[-0.30363888  1.49837   ]
  [-0.26625246 -0.7382212 ]]]

Kết quả phép cộng (Graph Execution):
 [[[ 0.7923929  -1.1253982 ]
  [-0.84200865  1.5837166 ]]

 [[-0.04928982 -0.31449473]
  [-1.5057263   2.005332  ]]

 [[-0.03044954  0.6124516 ]
  [ 0.68442035 -0.64712834]]]


In [7]:
#bai13
import tensorflow as tf


class AdditionModel(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)


    @tf.function
    def __call__(self, x, y):

        return tf.add(x, y)

sum_model = AdditionModel(name="sum_model")


x = tf.constant([10, 20], dtype=tf.int32)
y = tf.constant([5, 15], dtype=tf.int32)


result = sum_model(x, y)

print("Tensor x:", x.numpy())
print("Tensor y:", y.numpy())
print("Kết quả x + y từ model:", result.numpy())

Tensor x: [10 20]
Tensor y: [ 5 15]
Kết quả x + y từ model: [15 35]


In [8]:
#bai14
import tensorflow as tf

class MathModel(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)


    @tf.function
    def __call__(self, x, y):

        diff = tf.subtract(x, y)


        prod = tf.multiply(x, y)

        return diff, prod


my_math_model = MathModel(name="math_operations")

x = tf.constant([10, 20, 30], dtype=tf.float32)
y = tf.constant([2, 4, 6], dtype=tf.float32)

difference, product = my_math_model(x, y)

print("Tensor x:", x.numpy())
print("Tensor y:", y.numpy())
print("Hiệu (x - y):", difference.numpy())
print("Tích (x * y):", product.numpy())

Tensor x: [10. 20. 30.]
Tensor y: [2. 4. 6.]
Hiệu (x - y): [ 8. 16. 24.]
Tích (x * y): [ 20.  80. 180.]


In [9]:
#bai15
import tensorflow as tf


class RectanglePerimeterModel(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)


    @tf.function
    def __call__(self, a, b):

        sum_sides = tf.add(a, b)

        perimeter = tf.multiply(sum_sides, 2.0)

        return perimeter

model = RectanglePerimeterModel(name="perimeter_calculator")

a = tf.constant(10.0, dtype=tf.float32)
b = tf.constant(5.0, dtype=tf.float32)


result = model(a, b)

print(f"Chiều dài a: {a.numpy()}")
print(f"Chiều rộng b: {b.numpy()}")
print(f"Chu vi hình chữ nhật P: {result.numpy()}")

Chiều dài a: 10.0
Chiều rộng b: 5.0
Chu vi hình chữ nhật P: 30.0


In [10]:
#bai16
import tensorflow as tf


class BoxAreaModel(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)


    @tf.function
    def __call__(self, a, b, c):

        sum_ab = tf.add(a, b) #
        s_xung_quanh = tf.multiply(tf.multiply(sum_ab, c), 2.0) #


        s_day = tf.multiply(tf.multiply(a, b), 2.0)
        s_toan_phan = tf.add(s_day, s_xung_quanh)

        return s_xung_quanh, s_toan_phan


model = BoxAreaModel(name="box_area_calculator")

a = tf.constant(5.0, dtype=tf.float32)
b = tf.constant(3.0, dtype=tf.float32)
c = tf.constant(4.0, dtype=tf.float32)


sxq, stp = model(a, b, c)

print(f"Kích thước hộp: dài={a.numpy()}, rộng={b.numpy()}, cao={c.numpy()}")
print(f"Diện tích xung quanh: {sxq.numpy()}")
print(f"Diện tích toàn phần: {stp.numpy()}")

Kích thước hộp: dài=5.0, rộng=3.0, cao=4.0
Diện tích xung quanh: 64.0
Diện tích toàn phần: 94.0


In [11]:
#bai17
import tensorflow as tf

class ParallelSidesModel(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)

    @tf.function
    def __call__(self, AD, BC, AB, CD):

        cond1 = tf.equal(AD, BC)

        cond2 = tf.equal(AB, CD)

        is_parallel = tf.logical_and(cond1, cond2)
        return is_parallel


model_17 = ParallelSidesModel(name="check_parallel")
result = model_17(tf.constant(5), tf.constant(5), tf.constant(3), tf.constant(3))
print("Kết quả chứng minh AD // BC:", result.numpy())

Kết quả chứng minh AD // BC: True


In [12]:
#bai18
import tensorflow as tf

class EqualBasesModel(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)

    @tf.function
    def __call__(self, AD, BC, is_AD_parallel_BC):

        is_equal_sides = tf.equal(AD, BC)

        is_equal_bases = tf.logical_and(is_equal_sides, is_AD_parallel_BC)
        return is_equal_bases


model_18 = EqualBasesModel(name="check_equal_bases")

is_parallel = tf.constant(True)
result = model_18(tf.constant(4), tf.constant(4), is_parallel)
print("Kết quả chứng minh AB = CD:", result.numpy())

Kết quả chứng minh AB = CD: True


In [13]:
#bai19
import tensorflow as tf

class TriangleMidpointModel(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)

    @tf.function
    def __call__(self, AM, MB, is_MN_parallel_BC):
        """
        Chứng minh NA = NC dựa trên:
        1. M là trung điểm của AB (AM = MB)
        2. MN song song với BC
        """

        is_M_midpoint = tf.equal(AM, MB)

        can_conclude_NA_equal_NC = tf.logical_and(is_M_midpoint, is_MN_parallel_BC)

        return can_conclude_NA_equal_NC


model = TriangleMidpointModel(name="midpoint_proof_model")

AM_val = tf.constant(5.0)
MB_val = tf.constant(5.0)
parallel_cond = tf.constant(True)

result = model(AM_val, MB_val, parallel_cond)

print(f"Điều kiện AM = MB: {tf.equal(AM_val, MB_val).numpy()}")
print(f"Điều kiện MN // BC: {parallel_cond.numpy()}")
print(f"Kết luận NA = NC có đúng không? -> {result.numpy()}")

Điều kiện AM = MB: True
Điều kiện MN // BC: True
Kết luận NA = NC có đúng không? -> True
